name: andeangc
channels:
  - conda-forge
dependencies:
  - python=3.12

  # geospatial stack (conda-only, critical)
  - geopandas
  - rasterio
  - rioxarray
  - shapely
  - geocube
  - whitebox
  - exactextract
  - xagg
  - saqc
  - pyarrow
  - pyyaml
  - tqdm

  # notebooks / workflow
  - jupyter

  # install your package
  - pip
  - pip:
      - -e .
